# Generated by Django 5.2.6 on 2025-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
