# Generated by Django 5.2.6 on 2025-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_userprofile_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
