# Generated by Django 5.2.6 on 2025-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
