# Generated by Django 5.2.6 on 2025-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userprofile_instagram_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
