# Generated by Django 5.2.6 on 2025-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_college_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(max_length=500),
        ),
    ]
