# Generated by Django 5.2.6 on 2025-10-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_userprofile_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='eventapplicationdetails',
            name='college_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='follow',
            name='college_name',
            field=models.CharField(max_length=500),
        ),
    ]
