# Generated by Django 5.2.6 on 2025-10-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='conduct_aptitude_test',
            field=models.BooleanField(default=False, verbose_name='Include Aptitude Test Screening'),
        ),
    ]
