# Generated by Django 5.2.6 on 2025-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
