# Generated by Django 5.2.6 on 2025-10-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_college_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_icon',
            field=models.ImageField(blank=True, default='default_icon.png', null=True, upload_to='profile_icons/'),
        ),
    ]
