# Generated by Django 5.2.6 on 2025-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_aptitudetestattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplicationdetails',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
