# Generated by Django 5.2.6 on 2025-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_userprofile_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons/'),
        ),
    ]
