# Generated by Django 5.2.6 on 2025-10-19 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_eventapplicationdetails_is_shortlisted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='conduct_aptitude_test',
        ),
        migrations.AddField(
            model_name='event',
            name='screening_type',
            field=models.CharField(choices=[('none', 'No Screening'), ('aptitude', 'Aptitude Test'), ('video', 'Video Screening'), ('photo', 'Photo Screening')], default='none', max_length=10, verbose_name='Screening Round Type'),
        ),
        migrations.CreateModel(
            name='PhotoScreeningSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to='event_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Submission',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='VideoScreeningSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='event_videos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Submission',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
